### ISSUE TITLE
Questions about the "oss@oppo.com" mailbox

### ISSUE THREAD

**Issue by DavidWithTuxedo** [oppo/CameraUnit#3]
Once this mailbox was managed by the [oppo-source](github.com/oppo-source) and used to inquire about the kernel source of oppo mobile phones.

But recently this mailbox has been moved from the page of "oppo-source" here. I wonder if it still manages this aspect of things now or there is a new mailbox for the "oppo-source" ? 

Thanks in advance!

**Comment by DavidWithTuxedo** [comment]
Don't answer?

**Comment by kneep** [comment]
@DavidWithTuxedo Hello. Thanks for the reminder. The email address is restored now. And I'm closing this issue since it's irrelevant.
