### ISSUE TITLE
[Report] Application Opens fine but Camera Screen is Black.

### ISSUE THREAD

**Issue by techyminati** [oppo/CameraUnit#4]
Hello Developer, @lgyjg , i tried compiling it for my device realme RMX2185, I know this project is not supported on realme devices yet. but since realme devices run realmeUI which is based on ColorOS too, can you check logs? The App opens fine but camera screen is blackened out. Also do you have telegram / mail? if yes please drop if possible to debug issues.

Here is logcat: https://gist.github.com/techyminati/26293130e7ca7f43c1e6a6a90c049522

Thank You

**Comment by lgyjg** [comment]
Hello @techyminati ,

I have checked the log you posted, and found some error as follow:

```text
07-15 22:35:38.643 20046 20078 I MediaCodec: new MediaCodec()
07-15 22:35:38.645 20046 20046 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/ocs/camera/impl/CameraUnitImpl;
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.checkRuntimeEnvironment(CameraUnitClient.java:194)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.initialize(CameraUnitClient.java:143)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnit.getCameraClient(CameraUnit.java:31)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.adapter.cameraunit.CameraUnitAdapter.isPlatformSupported(CameraUnitAdapter.java:126)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.CameraController.init(CameraController.java:225)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.init(MainActivity.java:351)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivityPermissionsDispatcher.initWithPermissionCheck(MainActivityPermissionsDispatcher.java:22)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.onResume(MainActivity.java:335)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Activity.performResume(Activity.java:8133)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4531)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4577)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Looper.loop(Looper.java:237)
07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7817)
07-15 22:35:38.645 20046 20046 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
07-15 22:35:38.645 20046 20046 W System.err: Caused by: java.lang.ClassNotFoundException: com.coloros.ocs.camera.impl.CameraUnitImpl
07-15 22:35:38.645 20046 20046 W System.err: 	... 22 more
07-15 22:35:38.646 20046 20046 D MainActivity: onCameraError, errorCode: 5, errorMsg: Not supported by this device!
07-15 22:35:38.529  1508  1532 I chatty  : uid=1000(system) android.anim identical 1 line
```
It seems to be a problem that the CameraUnitImpl class cannot be found due to device incompatibility.

`onCameraError, errorCode: 5, errorMsg: Not supported by this device!` According to the exception info, it is because the device does not support CameraUnit.

We will confirm this problem with the realme team as soon as possible.

THANKS

**Comment by techyminati** [comment]
> Hello @techyminati ,
> 
> I have checked the log you posted, and found some error as follow:
> 
> ```
> 07-15 22:35:38.643 20046 20078 I MediaCodec: new MediaCodec()
> 07-15 22:35:38.645 20046 20046 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/ocs/camera/impl/CameraUnitImpl;
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.checkRuntimeEnvironment(CameraUnitClient.java:194)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.initialize(CameraUnitClient.java:143)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnit.getCameraClient(CameraUnit.java:31)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.adapter.cameraunit.CameraUnitAdapter.isPlatformSupported(CameraUnitAdapter.java:126)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.CameraController.init(CameraController.java:225)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.init(MainActivity.java:351)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivityPermissionsDispatcher.initWithPermissionCheck(MainActivityPermissionsDispatcher.java:22)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.onResume(MainActivity.java:335)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Activity.performResume(Activity.java:8133)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4531)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4577)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Looper.loop(Looper.java:237)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7817)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
> 07-15 22:35:38.645 20046 20046 W System.err: Caused by: java.lang.ClassNotFoundException: com.coloros.ocs.camera.impl.CameraUnitImpl
> 07-15 22:35:38.645 20046 20046 W System.err: 	... 22 more
> 07-15 22:35:38.646 20046 20046 D MainActivity: onCameraError, errorCode: 5, errorMsg: Not supported by this device!
> 07-15 22:35:38.529  1508  1532 I chatty  : uid=1000(system) android.anim identical 1 line
> ```
> 
> It seems to be a problem that the CameraUnitImpl class cannot be found due to device incompatibility.
> 
> `onCameraError, errorCode: 5, errorMsg: Not supported by this device!` According to the exception info, it is because the device does not support CameraUnit.
> 
> We will confirm this problem with the realme team as soon as possible.
> 
> THANKS



> Hello @techyminati ,
> 
> I have checked the log you posted, and found some error as follow:
> 
> ```
> 07-15 22:35:38.643 20046 20078 I MediaCodec: new MediaCodec()
> 07-15 22:35:38.645 20046 20046 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/ocs/camera/impl/CameraUnitImpl;
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.checkRuntimeEnvironment(CameraUnitClient.java:194)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnitClient.initialize(CameraUnitClient.java:143)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camera.CameraUnit.getCameraClient(CameraUnit.java:31)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.adapter.cameraunit.CameraUnitAdapter.isPlatformSupported(CameraUnitAdapter.java:126)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.camerax.CameraController.init(CameraController.java:225)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.init(MainActivity.java:351)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivityPermissionsDispatcher.initWithPermissionCheck(MainActivityPermissionsDispatcher.java:22)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.oplus.ocs.cameraunit.component.MainActivity.onResume(MainActivity.java:335)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.Activity.performResume(Activity.java:8133)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4531)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4577)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.os.Looper.loop(Looper.java:237)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7817)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 07-15 22:35:38.645 20046 20046 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
> 07-15 22:35:38.645 20046 20046 W System.err: Caused by: java.lang.ClassNotFoundException: com.coloros.ocs.camera.impl.CameraUnitImpl
> 07-15 22:35:38.645 20046 20046 W System.err: 	... 22 more
> 07-15 22:35:38.646 20046 20046 D MainActivity: onCameraError, errorCode: 5, errorMsg: Not supported by this device!
> 07-15 22:35:38.529  1508  1532 I chatty  : uid=1000(system) android.anim identical 1 line
> ```
> 
> It seems to be a problem that the CameraUnitImpl class cannot be found due to device incompatibility.
> 
> `onCameraError, errorCode: 5, errorMsg: Not supported by this device!` According to the exception info, it is because the device does not support CameraUnit.
> 
> We will confirm this problem with the realme team as soon as possible.
> 
> THANKS

Thanks @lgyjg for checking logcats :) , Ping me once you get info from Realme Dev Team, I'll be happy to test this project in Realme devices I own.

**Comment by lgyjg** [comment]
@techyminati 

After confirmation, RMX2185 is a realme C11. Unfortunately, it does not support CameraUnit. We currently have no plans to support the old machine. You can try debug on the latest released machine, such as realme X7 pro. Thanks.

**Comment by techyminati** [comment]
> @techyminati
> 
> After confirmation, RMX2185 is a realme C11. Unfortunately, it does not support CameraUnit. We currently have no plans to support the old machine. You can try debug on the latest released machine, such as realme X7 pro. Thanks.

@lgyjg Thanks for reply, I do have realme X7 Pro/ X7 Max testers too, I will try & report you here, Thnaks

**Comment by lgyjg** [comment]
You are welcome!

**Comment by techyminati** [comment]
@lgyjg Hello friend, I've tried application on realme X7 Max ( Latest Model ) RMX3031 , The app crashes same as above, logcats are here :
https://gist.github.com/techyminati/9dca299dc8f42deb717aad86f03e4534

OS: Stock ROM ( realmeUI ) Non Rooted

**Comment by lgyjg** [comment]
@techyminati  Hello friend, I am very sorry to reply you so late.
After confirming with realme related colleagues, RMX3031 is not support CameraUnit too.
Currently only the following models are supported：
```
RMX2121
RMX2176
RMX2177
RMX2173
RMX2175
RMX2071
RMX2111
RMX2112
```
I don’t know if you have any related device...

**Comment by techyminati** [comment]
![image](https://user-images.githubusercontent.com/63485082/129209806-fe00a9d4-a801-40ca-a58c-1ca034b2ba4a.png)

Hello mate @lgyjg , I just tried Camera Unit in RMX2121 (realme X7 Pro) , and it just works fine, Thanks for your help @lgyjg also do you plan to add support to realme X7 Max , Or any older devices? Thanks In Advance !!

**Comment by lgyjg** [comment]
There is no adaptation plan for the older devices currently.

**Comment by techyminati** [comment]
> There is no adaptation plan for the older devices currently.

Okay but about more new devices like Realme X7 Max ? Any possibility sir? Thanks in Advance :)
