### ISSUE TITLE
[OPPO A71] Request for kernel source

### ISSUE THREAD

**Issue by DavidWithTuxedo** [oppo/CameraUnit#5]
@lgyjg 
Dear OPPO Engineer, sorry to disturb you in your busy schedule.

I bought the "OPPO A71(CPH1717EX)" in 2017, and I couldn't find its kernel source in the [oppo-source](https://github.com/oppo-source) that you mentioned at #2 
![IMG_20210810_150504](https://user-images.githubusercontent.com/85795570/128823298-75491e0d-4ba8-4da0-8972-44cb7e019544.jpg)

And it seems that there was no update in that repository from 2016 to 2018
![IMG_20210810_150840](https://user-images.githubusercontent.com/85795570/128823597-40421dab-57d6-4859-a5c2-aa158efc2b7f.jpg)
Would you please tell me where to find it?

Thanks in advance!

**Comment by lgyjg** [comment]
I am not responsible for the kernel open source issues. You can send an email to oss@oppo.com for consultation.
Thanks

**Comment by King12689** [comment]
> I am not responsible for the kernel open source issues. You can send an email to [oss@oppo.com](mailto:oss@oppo.com) for consultation. Thanks

hello sir its been a while but oppo repositories is still not updated the requested kernel source and device tree source for Oppo A71 CPH1717 is still not there its been 6 years since the release but the sources is still not publish in the repository i hope you can see this message sir and hoping that the sources will be released. .

**Comment by lgyjg** [comment]
> 

I am SORRY about that. But release device's kernel source is not my work. I don't known specific plan about it. 
So, You'd better consult the relevant team with email or make a issue in kernel open source repo. 
Thanks.

**Comment by King12689** [comment]
> Contributor

thanks for reply but the email you gave is not working ive been trying to email them but the email is invalid
