### ISSUE TITLE
请问下按照CameraUnit配置文档，却发生错误

### ISSUE THREAD

**Issue by hzhou81** [oppo/CameraUnit#7]
当调用CameraUnit.getCameraClient(getAppContext())的时候getCameraClient返回的值是null，我在build.gradle里引用的是implementation 'com.coloros.ocs:camera:1.0.4'，在AndroidManifest.xml也添加了我申请成功的com.coloros.ocs.camera.AUTH_CODE这个meta-data,请问下为什么程序在进入CameraUnitClient的checkRuntimeEnvironment()方法的时候直接进入了catch(Error var5),由于这部分代码无法调试，所以我不知道是我什么地方设置的不对吗？请问OPPO大神！

**Comment by hzhou81** [comment]
我在控制台里看到
W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coloros/ocs/camera/impl/CameraUnitImpl;

**Comment by hzhou81** [comment]
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.coloros.ocs.camera.impl.CameraUnitImpl" on path: DexPathList

**Comment by hzhou81** [comment]
上面那个问题过了，现在又出现
E/CameraUnit: onConnectionFailed, authentication fail, errorCode: 1002, errorMessage: AUTHENTICATE_FAIL

**Comment by lgyjg** [comment]
您好，Demo App 能直接跑起来吗？DemoApp的AUTH_CODE是有效的，需要配合demo app的包名和签名即可使用。如果您是个人开发者，目前似乎官网还无法直接认证。
AUTHENTICATE_FAIL 错误说明您的App调用CameraUnit服务的时候，鉴权没通过。相关问题，您可以参考官网关于鉴权的内容：
https://open.oppomobile.com/new/developmentDoc/info?id=10719

**Comment by hzhou81** [comment]
demo app可以运行，能看到广角的镜头效果。我是企业开发者。我使用我司的包名和签名以及网站上告诉我的AUTH_CODE就会显示鉴权失败。如果需要收费，请告之我电话。

**Comment by lgyjg** [comment]
> 

你需要在开发者网站上使用贵司的应用包名和签名hash申请鉴权码，而不能使用网站上demo的AUTH_CODE，目前 CameraUnit API提供的功能是不收费的。谢谢

**Comment by lgyjg** [comment]
长时间未答复，关闭本问题
